# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/dmrch/banner/models/banner/columns.yaml

# Model Class name
modelClass: Dmrch\Banner\Models\Banner

# List Title
title: Gerenciar Banners

# Link URL for each record
recordUrl: dmrch/banner/banner/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: ordem
    direction: asc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
